version: '2'

services:
  zookeeper:
    image: wurstmeister/zookeeper
    networks:
      - main
    ports:
      - "2181:2181"

  kafka:
    image: wurstmeister/kafka:0.10.2.0-1
    networks:
      - main
    ports:
      - "9092:9092"
    environment:
      KAFKA_ADVERTISED_HOST_NAME: localhost
      KAFKA_ADVERTISED_PORT: 9092
      KAFKA_CREATE_TOPICS: testTopic:1:1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181

networks:
  main:
    driver: bridge